### ISSUE TITLE
Error after update to Angular 10

### ISSUE THREAD

**Issue by rayita** [IliaIdakiev/angular-material-timepicker#22]
Hi, we update our application to angular 10 and now we got this error:

```
Cannot read property 'firstCreatePass' of null

**Comment by IliaIdakiev** [comment]
I'm not sure what `firstCreatePass ` is. There is no property with that name inside this project. I suggest that you do a global search inside your project and maybe you will find why your project is failing. If you still believe that this issue is related with this library please provide a [stackblitz demo](https://stackblitz.com/). Thanks.

**Comment by rayita** [comment]
The problem is just that is not compatible with Angular Material 10, even your demo app do not work if stackblitz update Angular to version 10.

Here yo have an small app in startbltz [https://stackblitz.com/edit/components-issue-x1aufv](https://stackblitz.com/edit/components-issue-x1aufv)

And you can see the "ERROR Error: mat-form-field must contain a MatFormFieldControl."

For some weird reason inside a big app you get another funny messages that desapear when you remove matTimepiker.

Cheers.

**Comment by IliaIdakiev** [comment]
This error is because first you need to add the the MatTimepickerModule inside the imports of your module and second the name of the directive is `matTimepicker` not `matTimePicker`. I'm not sure why there is an error `NullInjectorError: No provider for Renderer2!` when testing in StackBlitz but it's possible that it's a StackBlitz issue.

**Comment by rayita** [comment]
Yes, you are right. I created the sample in a hurry and made some typos.
And agree, Renderer2 issue seems to be realted with StackBlitz, so I downloaded the sample, fixed it  and test in local, and i got the original 'firstCreatePasss' error.

[mat-timepicker-demo.zip](https://github.com/IliaIdakiev/angular-material-timepicker/files/4850066/mat-timepicker-demo.zip)

Sample attached.

**Comment by IliaIdakiev** [comment]
Try deleting node_modules folder and installing mat-timepicker@4.1.3 along the other dependencies for the project. It's working on my machine.

**Comment by rayita** [comment]
Version 4.1.3  works fine.

Thank you very much.

**Comment by IliaIdakiev** [comment]
You're welcome.
