### ISSUE TITLE
Change buttons styling

### ISSUE THREAD

**Issue by mathudak** [IliaIdakiev/angular-material-timepicker#34]
Hi,

is it possible to change buttons styling without some heavy hacking? We are utilizing mat-stroked button within the application and the dialog buttons don't meet that requirement.

Thanks

**Comment by IliaIdakiev** [comment]
Hello @mathudak. 

Thanks for opening this issue. I will put two new inputs that will accept a templateRef  for the buttons. If provided the templates will be used otherwise the default template will be used. I will add it in the next few days and I will close the issue when I'm done.

Cheers!

**Comment by IliaIdakiev** [comment]
@mathudak In v.5.1.0 I've added two new inputs for okButtonTemplate and cancelButtonTemplate that you can use in order to change the default buttons. I've added an example inside the demo app at the bottom of the template driven form inside the [example app](https://github.com/IliaIdakiev/angular-material-timepicker/blob/67dcbe072d7b2d407abbd0717a2f55074efe2fa9/src/app/app.component.html#L100). If you like the timepicker I would appreciate it giving it a star. Thanks for the issue again and cheers!

**Comment by mathudak** [comment]
Works great, thank you!
